USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_PRG_ACT]    Script Date: 05/04/2015 18:39:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PTS_PRG_ACT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IM] [varchar](150) NULL,
	[SICIL] [varchar](50) NULL,
	[MEMO] [varchar](150) NULL,
	[AID] [smallint] NULL,
	[UID] [smallint] NULL,
	[FDT] [datetime] NULL,
	[CLB] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_PRG_DEF_ACTLIST]    Script Date: 05/04/2015 18:39:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PTS_PRG_DEF_ACTLIST](
	[INTCODE] [int] IDENTITY(1,1) NOT NULL,
	[ACT] [varchar](50) NOT NULL,
	[ISRPC] [bit] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_PRG_DEF_ULSLST]    Script Date: 05/04/2015 18:40:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PTS_PRG_DEF_ULSLST](
	[INTCODE] [int] IDENTITY(1,1) NOT NULL,
	[ACT] [varchar](50) NOT NULL,
	[ISRPC] [bit] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_PRG_LOGS]    Script Date: 05/04/2015 18:40:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PTS_PRG_LOGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UID] [varchar](50) NULL,
	[LOGIN] [datetime] NULL,
	[LOGOUT] [datetime] NULL,
	[IM] [varchar](150) NULL,
	[ST] [tinyint] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_T_Dat_PREGRINE]    Script Date: 05/04/2015 18:40:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PTS_T_Dat_PREGRINE](
	[INTCODE] [int] IDENTITY(1,1) NOT NULL,
	[OLAYNO] [nvarchar](250) NULL,
	[ACILIS_TARIHI] [nvarchar](250) NULL,
	[GUNCELLEME_TARIHIi] [nvarchar](250) NULL,
	[UYARI_DURUMU] [nvarchar](250) NULL,
	[ANA_KATEGORI] [nvarchar](250) NULL,
	[KATEGORI] [nvarchar](250) NULL,
	[ALT_KATEGORI] [nvarchar](250) NULL,
	[Kanal] [nvarchar](250) NULL,
	[MUSTERI_ADI] [nvarchar](250) NULL,
	[MUSTERI_SOYADI] [nvarchar](250) NULL,
	[ATANAN_KISI] [nvarchar](250) NULL,
	[BASENO] [nvarchar](250) NULL,
	[ISLEMIN_GERCEKLESTIGI_KART_NO] [nvarchar](250) NULL,
	[ACIKLAMA] [nvarchar](max) NULL,
	[SLA_ASILDI] [nvarchar](250) NULL,
	[KART_SAHIBI_TAM_ADI] [nvarchar](250) NULL,
	[COZUM_GRUBU] [nvarchar](250) NULL,
	[KAPATAN_KULLANICI] [nvarchar](250) NULL,
	[ARAMA_SAYISI] [nvarchar](250) NULL,
	[GSM_NO] [nvarchar](250) NULL,
	[MUSTERI_TELEFON_NO] [nvarchar](250) NULL,
	[EK_VAR] [nvarchar](250) NULL,
	[TIP] [nvarchar](250) NULL,
	[SLA_EXPIRATION] [nvarchar](250) NULL
) ON [PRIMARY]

GO

USE [CCOps]
GO

/****** Object:  Table [dbo].[PTS_T_Tmp_PREGRINE]    Script Date: 05/04/2015 18:40:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PTS_T_Tmp_PREGRINE](
	[OLAYNO] [nvarchar](250) NULL,
	[ACILIS_TARIHI] [nvarchar](250) NULL,
	[GUNCELLEME_TARIHIi] [nvarchar](250) NULL,
	[UYARI_DURUMU] [nvarchar](250) NULL,
	[ANA_KATEGORI] [nvarchar](250) NULL,
	[KATEGORI] [nvarchar](250) NULL,
	[ALT_KATEGORI] [nvarchar](250) NULL,
	[Kanal] [nvarchar](250) NULL,
	[MUSTERI_ADI] [nvarchar](250) NULL,
	[MUSTERI_SOYADI] [nvarchar](250) NULL,
	[ATANAN_KISI] [nvarchar](250) NULL,
	[BASENO] [nvarchar](250) NULL,
	[ISLEMIN_GERCEKLESTIGI_KART_NO] [nvarchar](250) NULL,
	[ACIKLAMA] [nvarchar](max) NULL,
	[SLA_ASILDI] [nvarchar](250) NULL,
	[KART_SAHIBI_TAM_ADI] [nvarchar](250) NULL,
	[COZUM_GRUBU] [nvarchar](250) NULL,
	[KAPATAN_KULLANICI] [nvarchar](250) NULL,
	[ARAMA_SAYISI] [nvarchar](250) NULL,
	[GSM_NO] [nvarchar](250) NULL,
	[MUSTERI_TELEFON_NO] [nvarchar](250) NULL,
	[EK_VAR] [nvarchar](250) NULL,
	[TIP] [nvarchar](250) NULL,
	[SLA_EXPIRATION] [nvarchar](250) NULL
) ON [PRIMARY]

GO

USE [CCOps]
GO

/****** Object:  View [dbo].[PTS_VW_PREGRINE]    Script Date: 05/04/2015 18:41:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





   CREATE VIEW [dbo].[PTS_VW_PREGRINE] AS 
 select TOP 1232123   * from dbo.PTS_T_dat_PREGRINE
ORDER BY
 case UYARI_DURUMU
  WHEN 'DEADLINE ALERT' THEN 4
  WHEN 'Alert3' THEN 3
  WHEN 'alert stage 2' THEN 2
  WHEN 'Alert1' THEN 1 ELSE 0 END DESC,
  
   CASE KATEGORI WHEN 'KMH' THEN 
 CONVERT(VARCHAR(8), CONVERT(DATETIME,ACILIS_TARIHI,103)-1, 112)  
 else 
 CONVERT(VARCHAR(8), CONVERT(DATETIME,ACILIS_TARIHI,103), 112)  
end ASC,

 CASE KATEGORI WHEN 'KMH' THEN 2
 ELSE 0 END DESC ,

case ALT_KATEGORI WHEN 'RİSKLİ TİCARİ KARTLAR' THEN 1 else 0 end desc,

CASE TIP WHEN 'Objection' THEN 5
WHEN 'Exception' THEN 4
WHEN 'Request' THEN 3 
WHEN 'Application' THEN 2
WHEN 'Suggestion' THEN 1 
ELSE 0 END DESC,
CONVERT(DATETIME,ACILIS_TARIHI,103) asc 
 
/*
 select TOP 1232123   * from dbo.PTS_T_dat_PREGRINE
ORDER BY
 case UYARI_DURUMU
  WHEN 'DEADLINE ALERT' THEN 4
  WHEN 'Alert3' THEN 3
  WHEN 'alert stage 2' THEN 2
  WHEN 'Alert1' THEN 1 ELSE 0 END DESC,
 CONVERT(VARCHAR(8), CONVERT(DATETIME,ACILIS_TARIHI,103), 112) ASC
, CASE KATEGORI WHEN 'KMH' THEN 2
WHEN 'RİSKLİ TİCARİ KARTLAR' THEN 1
 ELSE 0 END DESC ,
CASE TIP WHEN 'Objection' THEN 5
WHEN 'Exception' THEN 4
WHEN 'Request' THEN 3 
WHEN 'Application' THEN 2
WHEN 'Suggestion' THEN 1 
ELSE 0 END DESC,
CONVERT(DATETIME,ACILIS_TARIHI,103) asc 
*/




GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_ACT]    Script Date: 05/04/2015 18:41:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/****** Script for SelectTopNRows command from SSMS  ******/

--------------------------------------------
------------  AKSIYON ALMA  ----------------
--------------------------------------------
CREATE PROC 
 [dbo].[PTS_PRG_SP_ACT] ( @SICIL VARCHAR(50),
 @IM VARCHAR(150),
 @MEMO VARCHAR(150),
 @AID SMALLINT,
 @UID SMALLINT ,@CLB VARCHAR(50)) AS
 /*
 PTS_PRG_SP_ACT 'A25318','54775051712','DENEME',3
EXEC PTS_PRG_SP_ACT 'A25318','000005IM17868999','de',17,0,'29/04/2015 12:50:00'

 CREATE TABLE PTS_PRG_ACT(
 ID INT IDENTITY(1,1),
 IM VARCHAR(150),
 SICIL VARCHAR(50),
 MEMO VARCHAR(150),
 AID SMALLINT ,
 FDT DATETIME
 )
 
 SELECT * FROM  PTS_PRG_ACT
 SELECT * FROM  PTS_PRG_LOGS
 */
 DECLARE @KONTROL INT;

 select @KONTROL = ISNULL(COUNT(*),0) from PTS_PRG_USERS
 WHERE UID =@SICIL


IF ISNULL(@KONTROL,0) >0 
BEGIN


 INSERT INTO PTS_PRG_ACT(IM,SICIL,MEMO,AID,UID,FDT,CLB)
 VALUES(@IM,@SICIL,@MEMO,@AID,@UID,GETDATE(),CONVERT(DATETIME,@CLB,103));
 
 UPDATE PTS_PRG_LOGS
 SET ST=1
 WHERE UID=@SICIL AND IM=@IM;
 
 END 
ELSE 
BEGIN 

SELECT '0' AS RV
END
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_ACTLIST]    Script Date: 05/04/2015 18:41:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create PROC 
 [dbo].[PTS_PRG_SP_ACTLIST]  AS
 
 
 
 SELECT * FROM PTS_PRG_DEF_ACTLIST
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_AKTIVE]    Script Date: 05/04/2015 18:41:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[PTS_PRG_SP_AKTIVE]( @SICIL VARCHAR(50)) AS
/*
SAYFA POSTBACK DEGIL.
AKTIF KAYIT VARSA DEVAM ETTIRILECEK YOKSA BUTONLAR AKTIF YAPILACAK
*/
 
--DECLARE @SICIL VARCHAR(50)='A25318';
DECLARE @RIM VARCHAR(150);
DECLARE @VIM VARCHAR(150);
DECLARE @KONTROL INT;

 select @KONTROL = ISNULL(COUNT(*),0) from PTS_PRG_USERS
 WHERE UID =@SICIL


IF ISNULL(@KONTROL,0) >0 
BEGIN

SELECT  TOP 1  @RIM=IM 
FROM PTS_PRG_LOGS
WHERE UID=@SICIL 
AND LOGOUT>GETDATE()
AND ST=0;

IF ISNULL(@RIM,'0') ='0' 
BEGIN
 SET @VIM ='0'
 END
 ELSE 
 BEGIN
 
 --AKTIF KAYIT VAR, LOGOUT SURESI ARTTIRILIR
UPDATE PTS_PRG_LOGS
SET LOGOUT=DATEADD(MINUTE,20,GETDATE())
WHERE UID=@SICIL 
AND LOGOUT>GETDATE()
AND ST=0
AND IM=@RIM ;
 
SET @VIM =@RIM;


END
 SELECT @VIM AS RV,DATEADD(MINUTE,20,GETDATE()) LOGOUT;

END 

ELSE 
BEGIN 

SELECT '0' AS RV
END
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_GETRPR]    Script Date: 05/04/2015 18:42:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC 
 [dbo].[PTS_PRG_SP_GETRPR] (  @SDT VARCHAR(50) ,@FDT VARCHAR(50)) AS
 
 declare @BASLA datetime  
 DECLARE @BITIR DATETIME  
 
SET @BASLA = CONVERT(DATETIME,@SDT,103);
 SET @BITIR = CONVERT(DATETIME,@FDT,103);
  
-- SET @BASLA = CONVERT(DATETIME,'29/04/2015 12:00:47.547',103);
 -- SET @BITIR = CONVERT(DATETIME,'29/04/2015 13:00:47.547',103);
  
 SELECT * FROM(
 SELECT * FROM  PTS_PRG_ACT
 WHERE FDT BETWEEN  @BASLA AND @BITIR
 ) A LEFT JOIN  dbo.PTS_PRG_LOGS B 
 ON  A.IM= B.IM AND A.SICIL=B.UID -- AND A.FDT < LOGOUT AND A.FDT>  LOGIN 
 ORDER BY A.IM
 
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_HISTORY]    Script Date: 05/04/2015 18:42:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[PTS_PRG_SP_HISTORY]( @IM VARCHAR(50)) AS

 
  SELECT * FROM PTS_PRG_ACT a left join dbo.PTS_PRG_DEF_ACTLIST b on a.AID=b.INTCODE left join PTS_PRG_DEF_ULSLST c   on a.UID=c.INTCODE
  WHERE RIGHT(CONVERT(VARCHAR(50),IM),10) =RIGHT(@IM,10)
  ORDER BY fdt 

 
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_IM]    Script Date: 05/04/2015 18:42:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[PTS_PRG_SP_IM]( @SICIL VARCHAR(50)) AS
/*

PTS_PRG_SP_IM 'A25318'


create table PTS_PRG_LOGS
(ID int identity(1,1),
UID varchar(50),
LOGIN datetime,
LOGOUT datetime,
IM varchar(150),
ST TINYINT)*/

--LISTEDE TEPEDEKINI GETIRIYOR
--DECLARE @SICIL VARCHAR(50)='A25318';
DECLARE @RIM VARCHAR(150);
DECLARE @VIM VARCHAR(150);

SELECT TOP 1  @RIM=IM 
FROM PTS_PRG_LOGS
WHERE UID=@SICIL 
AND LOGOUT>GETDATE()
AND ST=0;

IF ISNULL(@RIM,'0') ='0' 
BEGIN
 
SELECT    TOP 1  @VIM= 
 convert(varchar(6),right(replicate('0',6) + cast(INTCODE as varchar),6)) + CONVERT(VARCHAR(150),OLAYNO) 
FROM dbo.PTS_VW_PREGRINE A--PTS_T_dat_PREGRINE A
WHERE NOT EXISTS (SELECT * FROM PTS_PRG_ACT B WHERE --A.OLAYNO=B.IM 
a.INTCODE=CONVERT(INT,LEFT(b.IM,6))
--SON 3 GUNDE AKSIYON ALINDIYSA LISTEDEN GELMEZ.AND  DATEDIFF(DAY,B.FDT,GETDATE())<3 
AND  CASE WHEN AID=17 AND CLB<GETDATE() THEN 1 ELSE 0 END =0
)
AND NOT EXISTS (SELECT * 
FROM PTS_PRG_LOGS B
WHERE  LOGOUT>GETDATE()
AND ST=0 AND a.INTCODE=CONVERT(INT,LEFT(b.IM,6))-- A.OLAYNO=B.IM  
)

;
 
INSERT INTO PTS_PRG_LOGS(UID,LOGIN,LOGOUT,IM,ST)VALUES(@SICIL,GETDATE(), DATEADD(MINUTE,20,GETDATE()),@VIM,0);

SELECT @VIM AS RV


END
ELSE
BEGIN
SELECT @RIM AS RV
END



GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_IMSEARCH]    Script Date: 05/04/2015 18:42:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[PTS_PRG_SP_IMSEARCH]( @IM VARCHAR(50),@SICIL VARCHAR(50)) AS


DECLARE @KONTROL INT;

 select @KONTROL = ISNULL(COUNT(*),0) from PTS_PRG_USERS
 WHERE UID =@SICIL


IF ISNULL(@KONTROL,0) >0 
BEGIN


DECLARE @NIM VARCHAR(150);

select  @NIM= MAX(convert(varchar(6),right(replicate('0',6) + cast(INTCODE as varchar),6)) + CONVERT(VARCHAR(150),OLAYNO))
FROM dbo.PTS_VW_PREGRINE A 
WHERE OLAYNO = @IM


--PRINT @NIM

--DECLARE @IM VARCHAR(50)='25508059138';
DECLARE @RIM VARCHAR(150);
DECLARE @VIM VARCHAR(150);

SELECT  TOP 1  @RIM=UID
FROM PTS_PRG_LOGS
WHERE IM = @NIM
AND LOGOUT>GETDATE()
AND ST=0;



IF ISNULL(@RIM,'0') ='0' 
BEGIN
 


INSERT INTO PTS_PRG_LOGS(UID,LOGIN,LOGOUT,IM,ST)VALUES(@SICIL,GETDATE(), DATEADD(MINUTE,20,GETDATE()),@NIM,0);

SELECT @NIM AS RV


END
ELSE
BEGIN
SELECT @RIM AS RV
END






END 
ELSE 
BEGIN 

SELECT '0' AS RV
END
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_ONLINE]    Script Date: 05/04/2015 18:42:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[PTS_PRG_SP_ONLINE] AS
--DECLARE  @TABLO TABLE( SICIL VARChar( 30 ),ACT VARCHAR(50),ADET integer ); 
 IF OBJECT_ID('tempdb..#tempdbname') IS NOT NULL     --Remove dbo here 
    DROP TABLE #tempdbname 
 
SELECT * INTO #tempdbname  FROM (select SICIL,ACT,COUNT(*) ADET
from dbo.PTS_PRG_ACT a left join dbo.PTS_PRG_DEF_ACTLIST b
on a.AID=b.INTCODE
where datediff(day,FDT,getdate())=0
group by SICIL,ACT)X

DECLARE @ACT VARCHAR(50);
DECLARE @QUERY VARCHAR(MAX);
SET @QUERY='SELECT SICIL ';

 DECLARE CURSOR3 CURSOR FOR
SELECT  DISTINCT ACT
FROM PTS_PRG_DEF_ACTLIST
 OPEN CURSOR3;
FETCH NEXT FROM CURSOR3 INTO @ACT;
WHILE @@FETCH_STATUS = 0
   BEGIN
 SET @QUERY  =@QUERY+ ',SUM(CASE ACT WHEN '''+@ACT+''' THEN ADET ELSE 0 END) AS ['+@ACT+']'
       FETCH NEXT FROM CURSOR3 INTO @ACT;
   END;
CLOSE CURSOR3;
DEALLOCATE CURSOR3;
SET @QUERY=  @QUERY+', count(*) TOPLAM FROM #tempdbname GROUP BY SICIL'

EXEC (@QUERY)

GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_PREGRINE]    Script Date: 05/04/2015 18:42:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[PTS_PRG_SP_PREGRINE]( @IM VARCHAR(50)) AS

--TEK KAYIT MI GELECEK?  TOP 1 YAPILABILIR TARIHE GORE...

select top 1 
* from dbo.PTS_VW_PREGRINE--dbo.PTS_T_dat_PREGRINE
WHERE INTCODE=CONVERT(INT,LEFT(@IM,6))-- OLAYNO= @IM
ORDER BY ACILIS_TARIHI

 
GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_PRG_SP_TRUNCATE]    Script Date: 05/04/2015 18:42:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE  PROC [dbo].[PTS_PRG_SP_TRUNCATE] AS
 TRUNCATE TABLE  dbo.PTS_T_Tmp_PREGRINE;

GO

USE [CCOps]
GO

/****** Object:  StoredProcedure [dbo].[PTS_SP_PREGRINE_FILE_FIN]    Script Date: 05/04/2015 18:43:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 

CREATE  proc [dbo].[PTS_SP_PREGRINE_FILE_FIN] as

delete from KRDPRDGEN01.CCOPS.dbo.PTS_T_Dat_PREGRINE
WHERE  EXISTS (
SELECT 1
FROM KRDPRDGEN01.CCOPS.dbo.PTS_T_tmp_PREGRINE  B
WHERE  PTS_T_Dat_PREGRINE.OLAYNO = B.OLAYNO 
AND PTS_T_Dat_PREGRINE.GUNCELLEME_TARIHIi=B.GUNCELLEME_TARIHIi
--AND A.GUNCELLEME_TARIHIi=B.GUNCELLEME_TARIHIi
)


INSERT INTO KRDPRDGEN01.CCOPS.dbo.PTS_T_Dat_PREGRINE (OLAYNO, ACILIS_TARIHI, GUNCELLEME_TARIHIi, UYARI_DURUMU, ANA_KATEGORI, KATEGORI, ALT_KATEGORI, Kanal, MUSTERI_ADI, MUSTERI_SOYADI, ATANAN_KISI, BASENO, ISLEMIN_GERCEKLESTIGI_KART_NO, ACIKLAMA, SLA_ASILDI, KART_SAHIBI_TAM_ADI, COZUM_GRUBU, KAPATAN_KULLANICI, ARAMA_SAYISI, GSM_NO, MUSTERI_TELEFON_NO, EK_VAR, TIP, SLA_EXPIRATION)
SELECT OLAYNO, ACILIS_TARIHI, GUNCELLEME_TARIHIi, UYARI_DURUMU, ANA_KATEGORI, KATEGORI, ALT_KATEGORI, Kanal, MUSTERI_ADI, MUSTERI_SOYADI, ATANAN_KISI, BASENO, ISLEMIN_GERCEKLESTIGI_KART_NO, ACIKLAMA, SLA_ASILDI, KART_SAHIBI_TAM_ADI, COZUM_GRUBU, KAPATAN_KULLANICI, ARAMA_SAYISI, GSM_NO, MUSTERI_TELEFON_NO, EK_VAR, TIP, SLA_EXPIRATION  
FROM KRDPRDGEN01.CCOPS.dbo.PTS_T_Tmp_PREGRINE A
WHERE NOT EXISTS (
SELECT 1
FROM KRDPRDGEN01.CCOPS.dbo.PTS_T_Dat_PREGRINE  B
WHERE A.OLAYNO = B.OLAYNO 
AND A.GUNCELLEME_TARIHIi=B.GUNCELLEME_TARIHIi
--AND A.GUNCELLEME_TARIHIi=B.GUNCELLEME_TARIHIi
)


EXEC  KRDPRDGEN01.CCOPS.dbo.PTS_PRG_SP_TRUNCATE
 

declare @yazi varchar(max) =' <style>     
body{

    font-family: Arial Narrow, Verdana, Sans-Serif;
    font-size: 11pt;
}
</style> 
DOSYA AKTARIMI GERCEKLESMISTIR.
<br/><br/>
 
  <a href="\\..\..\PREGRINE_FOLDER">PREGRINE_FOLDER</a>  
<br/><br/> ';




 exec msdb.dbo.sp_send_dbmail 
      @profile_name = '--',
  @recipients = '--',
-- @recipients = '--',
-- @copy_recipients='--',
      @subject = 'PREGRINE FILE TRANSFER',
      @body =@yazi,
      @body_format = 'HTML' 
 
     



GO

